# Generated by Django 4.0.4 on 2022-04-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('bith_date', models.DateField()),
                ('imafe', models.ImageField(upload_to='')),
            ],
        ),
    ]
