# Generated by Django 4.0.4 on 2022-04-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galary', '0003_person_delete_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='surname',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='person',
            name='bithdate',
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
