# Generated by Django 4.0.4 on 2022-04-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galary', '0004_rename_surname_person_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='product',
        ),
    ]
